# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SP9d-EEslRZPSlEJnZQv3VDSKc65fN8g
"""

import numpy as np
asientosN=np.array(
    [
     [1,2,3,4,5,6],
     [7,8,9,10,11,12],
     [13,14,15,16,17,18],
     [19,20,21,22,23,24],
     [25,26,27,28,29,30]
     ]
    )

asientosV=np.array(
    [
     [31,32,33,34,35,36],
     [37,38,39,40,41,42]
     ]
    )

datos=[]
total=0
x="x"
def asientosDis (opcion):
  if opcion==1:
    print(np.concatenate((asientosN, asientosV), axis=0))
 
asientosDis(1)

def comprarAsi (opcion):
  if opcion==2:
    print("Ingrese sus datos")
    datos=[]
    nombre=input("ingrese su nombre")
    datos.append(nombre)
    rut=input("ingrese su rut")
    datos.append(rut)
    telefono=int(input("ingrese su numero celular"))
    datos.append(telefono)
    
    banco=input("ingrese su banco, si pertenece a banco Duoc presione uno para obtener un descuento")
    # if banco=='1':
      # total*=0.15

    datos.append(banco)

    print("escoja uno de los asientos disponible")
    print(np.concatenate((asientosN, asientosV), axis=0))
    comprado=input()
    
    for i, value in enumerate(asientosN):
      if value == comprado:
        asientosN[i] = x

    
        
    
    
    
   
    asientosN





    print(datos)

comprarAsi(2)


# def anularVue (opcion):
  # if opcion==3:


# def modificarDat ():

# def salir ():
# datos:[]
# print()

lista=[
     [2,-5,-11,0],
     [-9,4,6,3],
     [4,7,12,-2]
     ]
matriz=np.array(lista)
print(matriz)

print(lista[1][3])
print(lista[0][2])
print(matriz[0,3])

for fila in matriz:
  for celda in fila:
    print(celda)

for i in range(len(matriz)):
  for j in range(len(matriz[i])):
    print(f"({i},{j}):{matriz[i,j]}")